name: Book

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:    
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        r-version: [4.0.3]

    steps:
      - uses: actions/checkout@v2
      - name: Install R
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.r-version }}
      - name: Install renv
        uses: r-lib/actions/setup-renv@v1
      - name: Install Pandoc
        uses: r-lib/actions/setup-pandoc@v1
        with:
          pandoc-version: '2.14.2'
      - name: Deploy the book
        run: sh ./scripts/moveFile.sh
